# Generated by Django 4.1.7 on 2023-04-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_chefs_facebook_chefs_instagram_chefs_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='causes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.events'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='instagram',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='special',
            name='desk',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='special',
            name='ingredients',
            field=models.CharField(max_length=100),
        ),
    ]
