# Generated by Django 4.1.7 on 2023-04-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_events_causes_alter_chefs_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='causes',
            new_name='caus',
        ),
    ]
