# Generated by Django 4.1.7 on 2023-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_causes_events_caus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='caus',
        ),
        migrations.AddField(
            model_name='events',
            name='desc_caus',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
