# Generated by Django 4.1.7 on 2023-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_chefs_facebook_alter_chefs_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='desc_caus',
            new_name='last_desc',
        ),
        migrations.AddField(
            model_name='events',
            name='desc_caus_1',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='desc_caus_2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='desc_caus_3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='desc_caus_4',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
