# Generated by Django 4.1.7 on 2023-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_desc_caus_events_last_desc_events_desc_caus_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('desc_caus_1', models.TextField(blank=True, max_length=1000)),
                ('desc_caus_2', models.TextField(blank=True, max_length=1000)),
                ('desc_caus_3', models.TextField(blank=True, max_length=1000)),
                ('last_desc', models.TextField(max_length=2000)),
                ('photo', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name_plural': 'Про ресторан',
            },
        ),
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='reviews'),
        ),
    ]
