# Generated by Django 4.1.7 on 2023-04-15 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_about_alter_reviews_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number is waited n format 380xx xxx xx xx', regex='^+?3?8?0?\\d{2}[- ]?(\\d[ -]?){7}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_response', models.DateTimeField(auto_now=True)),
                ('data_request', models.DateTimeField(auto_now_add=True)),
                ('people', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-data_request',),
            },
        ),
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, upload_to='reviews'),
        ),
    ]
