# Generated by Django 4.1.7 on 2023-04-20 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_booktable_alter_reviews_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number is waited n format 380xx xxx xx xx', regex='^\\+?3?8?0?\\d{2}[- ]?(\\d[ -]?){7}$')]),
        ),
    ]
