# Generated by Django 4.1.7 on 2023-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_booktable_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('is_proccesed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Повідомлення',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='booktable',
            options={'ordering': ('-data_request',), 'verbose_name_plural': 'Замовлення'},
        ),
    ]
